version: 0.2

phases:
  install:
    commands:
    - echo "installing node..."
    - curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
    - apt install -y nodejs
    - echo "installing yarn through npm..."
    - npm install --global yarn
  pre_build:
    commands:
      - yarn

  build:
    commands:
      - echo Build started on `date`
      - mvn install
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
    # - target/messageUtil-1.0.jar
