version: 0.2

phases:
  install:
    commands:
    - echo "installing node..."
    - curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
    - apt install -y nodejs

    - echo "installing yarn ..."
    - corepack enable
    - yarn init -2
    - yarn set version stable
    # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    # - apt update
    # - apt install --no-install-recommends yarn
    - echo "installed yarn..."
    - echo "Yarn version is:" yarn --version
  pre_build:
    commands:
      - echo "Yarn install dependencies..."
      - yarn install
      - echo "Done installing dependencies..."


  build:
    commands:
      - echo "Build started on date ...""
      - mvn install
      - echo "Done mvn install..."

  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
    # - target/messageUtil-1.0.jar
